### ISSUE TITLE
Linux x64 game hangs on black loading screen just before main menu

### ISSUE THREAD

**Issue by jcb47769** [Galileo88/OPM_Galileo#1]
Fresh install, fresh download of OPM, latest version of Kopernicus, game hangs on the loading screen before the opening menu can even come up.  Not the screen with the pictures and talking about module manager and parts etc, but the fraction of a second later where the screen goes black and the Loading... icon appear with the spinny planets just before the main menu appears.
A pathing issue maybe? it's trying to find GameData on my desktop, which is definitely not where it lives.  Linux is extra finicky about filenames and paths...
I also posted this in the forum but trying to do it right :)

[KSP_log.txt](https://github.com/Galileo88/OPM_Galileo/files/1163945/KSP_log.txt)

**Comment by Galileo88** [comment]
I don't know why it is doing this. The paths in the cfgs do not point to the desktop either. Like I said in the forum thread, this seems to be an issue with kopernicus. I'll double check on my side before reporting this issue to the kopernicus dev.
