### ISSUE TITLE
Gravity scan gives incorrect flavor text

### ISSUE THREAD

**Issue by dmarcuse** [Galileo88/OPM_Galileo#11]
Around Sarnus (and maybe the other planets), the gravity scan gives incorrect flavor text. I think it has to do with how the gravity scan uses biomes in low orbit, unlike the other sensors.

![Gravity scan using goo flavor text](https://user-images.githubusercontent.com/5429337/33623298-88dce7f4-d9be-11e7-8433-39e27116084b.png)

![Gravity scan using thermometer flavor text](https://user-images.githubusercontent.com/5429337/33623328-a1fd502a-d9be-11e7-9aef-fc3174b27d7a.png)

**Comment by Poodmund** [comment]
I can confirm this issue. The science definitions in the Localization file are not tied to the any experiment class and therefore any experiment in a region/zone could display a message from any experiment type.

EDIT: I'll fix it this evening.

**Comment by Poodmund** [comment]
This is a bigger issue than I thought it was; it is going to take me quite a bit longer as the localization and science defs files are quite borked. I'll get to it.

**Comment by dmarcuse** [comment]
Glad to hear the mod is still being updated - it's not a critical issue, so I wouldn't worry about how long it takes

**Comment by Poodmund** [comment]
@apemanzilla would you be able to download and test the files changed in the latest commit?

https://github.com/Galileo88/OPM_Galileo/commit/50adb9d6be2e3a71bbafbe5288623835338f9308

These should fix all the science definition issues.

**Comment by dmarcuse** [comment]
I haven't played KSP in a few months, but I'll take a look if I have spare time.

**Comment by Poodmund** [comment]
I think this is all now resolved with commit: https://github.com/Galileo88/OPM_Galileo/commit/fd60fb115bacba678973563fced66113571ad560
