### ISSUE TITLE
MM 3.0.1 FTW

### ISSUE THREAD

**Issue by Sigma88** [Galileo88/OPM_Galileo#13]
[OPM_ScienceDefs.cfg](https://github.com/Galileo88/OPM_Galileo/blob/master/GameData/OPM/OPM_ScienceDefs.cfg#L1) is broken when using 3.0.1

do you want me to fix it and make a PR?

**Comment by Sigma88** [comment]
hmm it would appear it is not broken in the master branch *scratch head*

**Comment by JadeOfMaar** [comment]
Sure, dude. :) 👍 
There's a branch other than Master? lol

**Comment by Sigma88** [comment]
apparently the files in the release are not the same

I just downloaded the release again to make sure, and the cfg in question has this line:

```
@EXPERIMENT_DEFINITION[*]:HAS[#id[surfaceSample]]
```
which is not correct while the master branch has this: 
```
@EXPERIMENT_DEFINITION:HAS[#id[surfaceSample]]
```

which is correct
