### ISSUE TITLE
Redo all biome maps to remove DXT1 compression and convert to Indexed .png format.

### ISSUE THREAD

**Issue by Poodmund** [Galileo88/OPM_Galileo#16]
As title states, all biome maps have artifacting due to DXT1 compression. A biome map pass should be done to remove all of this and converted to the indexed .png format in preparation for possible indexed .dds implementation in Kopernicus.

**Comment by CaptRobau** [comment]
Hey Pood,

I'll try to rustle up all the old sourcefiles for the biomes. Should make your job a little easier.

**Comment by Poodmund** [comment]
That would be handy if you have them. Anything else you also may think would be helpful... I'm a willing recipient. 😄  

If you need somewhere to send them to my email is poodmundgaming@gmail.com .

**Comment by Poodmund** [comment]
Resolved with commit: https://github.com/Galileo88/OPM_Galileo/commit/fd60fb115bacba678973563fced66113571ad560
