### ISSUE TITLE
It seems that OPM does not work for me :(

### ISSUE THREAD

**Issue by ultimatecrackdown** [Galileo88/OPM_Galileo#17]
[KSP.log](https://github.com/Galileo88/OPM_Galileo/files/1886214/KSP.log)

![image](https://user-images.githubusercontent.com/7334381/38453296-7952e554-3a53-11e8-93d2-f7d0d3d792e0.png)

**Comment by Poodmund** [comment]
You're using Kopernicus 1.4.2-1 on KSP 1.4.1.2089 which Kopernicus does not support.

Please update your KSP to version 1.4.2 and it will function.
