### ISSUE TITLE
Duplicate Textures for CTTP

### ISSUE THREAD

**Issue by BararQ** [Galileo88/OPM_Galileo#18]
Hi Galileo88, 

Noticed this pull request -> CTTP move out and Tekto colour map amended #8

Removed CTTP textures from the repo and re-pathed the terrain textures to read from GameData/CTTP/Textures for the CTTP re-basing.

I was just manually updating OPM to 1.2.6. I noticed that it comes with a packaged CTTP. I already had CTTP v1.0.2 installed. Reviewing the files, I found they had a different file structures. 
 
On the OPM 1.2.6 files, the 16 included textures sit in the PluginData Folder. 
GameData\CTTP\Textures\PluginData

These same identical 16 texture in CTTP v1.0.2 sit in
GameData\CTTP\Textures

I looked in the OPM 1.2.6 KopernicusConfigs and they all point to CTTP/Textures/PluginData/

I also downloaded latest version from CKAN and github, and it does not DL the CTTP with the textures in GameData\CTTP\Textures\PluginData. 

So if one were to install this from CKAN, it would fail to install correctly, may still run though. Only if you manually install the CTTP folder that comes with OPM 1.2.6 will it work correctly.

Is there any other reason why OPM is loading their own exclusive set of textures. It looks like it was planned to re-path them from the pull request but was never completed. 

It could be an easy fix, just find and replace CTTP/Textures/PluginData with CTTP/Textures/ in all the KopernicusConfigs. Then move the files in the OPM_Galileo-1.2.6 CTTP/Textures/PluginData folder up into CTTP/Textures folder to match CTTP layout.

Let me know if I am crazy.

**Comment by Poodmund** [comment]
The GameData\CTTP\Textures\PluginData should be the correct path. 

It seems as though the CTTP build that CKAN has indexed may not be correct. Let me take a look.

EDIT: Yep, CTTP needs updating. Thank you for letting us know.

**Comment by BararQ** [comment]
Mods like Extrasolar: Planets Beyond Kerbal expect those textures to be in GameData\CTTP\Textures, if you move them to GameData\CTTP\Textures\PluginData, it will affect that mod. I have not used any other Planet Pack mods, but if any have come to rely on CTTP. It might bugger up their setups. 

See below is a excerpt from the Serex.cfg Planet in Extrasolar 1.7 using CTTP textures.

				lowTex = CTTP/Textures/cracked
				lowTexScale = 1,1
				lowTexOffset = 0,0
				lowBumpMap = CTTP/Textures/cracked_normal
				lowBumpMapScale = 1,1
				lowBumpMapOffset = 0,0
				lowNearTiling = 200
				lowMultiFactor = 7
				lowBumpNearTiling = 200
				lowBumpFarTiling = 7
				midTex = CTTP/Textures/gravel
				midTexScale = 1,1
				midTexOffset = 0,0
				midBumpMap = CTTP/Textures/gravel_normal
				midBumpMapScale = 1,1
				midBumpMapOffset = 0,0
				midNearTiling = 200
				midMultiFactor = 7
				midBumpNearTiling = 200
				midBumpFarTiling = 7
				highTex = CTTP/Textures/gravel
				highTexScale = 1,1
				highTexOffset = 0,0
				highBumpMap = CTTP/Textures/gravel_normal

It is why I posted on this OPM_Galileo github not on the CTTP github.

So I just re-down loaded CTTP v1.0.2 from Github. It show the file structure GameData\CTTP\Textures as I seen from CKAN, I do not see a PluginData folder on any other version of CTTP except in OPM_Galileo.

Updating CTTP to GameData\CTTP\Textures\PluginData looks to me like it will break other planet packs that use CTTP and rely on it.

To me it makes sense the textures are in the textures folder.

**Comment by Galileo88** [comment]
they were moved to a PluginData folder as this saves ram and speeds up initial load of the game. CTTP has been updated and has the same file structure now. All other pplanet packs that depend on CTTP will need to update to avoid having duplicate textures.

**Comment by Poodmund** [comment]
@BararQ - Thank you for informing us about the Extrasolar mod. I have informed AndrewDrawsPrettyPictures here about the change: https://forum.kerbalspaceprogram.com/index.php?/topic/130656-142-extrasolar-v171-4918/&do=findComment&comment=3351042
