### ISSUE TITLE
Wal and Slate config errors for .dds 

### ISSUE THREAD

**Issue by BararQ** [Galileo88/OPM_Galileo#19]
Hi,

For Wal.cfg, there is a space behind Wal_normal, so it wont use OnDemandLoad.

ScaledVersion
        {
			fadeStart = 92500
			fadeEnd = 185000			
            Material
            {					
                texture = OPM/OPM_Textures/PluginData/Wal_color.dds
		        normals = OPM/OPM_Textures/PluginData/Wal_normal			.dds
            }
        }

For Slate.cfg, there is a space behind Slate_normal, so it wont use OnDemandLoad

ScaledVersion
        {
			fadeStart = 135000
			fadeEnd = 270000
            Material
            {	
                texture = OPM/OPM_Textures/PluginData/Slate_color.dds
		        normals = OPM/OPM_Textures/PluginData/Slate_normal	.dds
            }
        }

**Comment by Poodmund** [comment]
Thank you for the notification of this issue. A new release will be issued today to hotfix the error.
