### ISSUE TITLE
Yellow stripes with KSS+OPM

### ISSUE THREAD

**Issue by davidson16807** [Galileo88/OPM_Galileo#20]
Related issue reported for KSS here: https://github.com/StarCrusher96/Kerbal-Star-Systems/issues/4

The issue looks as follows: ![](https://i.imgur.com/lCHuIRj.jpg)

I'm running Linux Mint 17.2, and from what I hear, this occurs because OpenGL can't handle something concerning dds textures. 

I have both OPM and KSS installed. This issue never occur with just one mod installed. This leads me to believe it's something to do with the quantity of dds textures. It could also be a cfg file setting, but I can't think of any cfg setting that has a global effect on planets. 

On my machine, I've batch converted all dds textures from KSS to png and pointed the cfg files to the png versions. The issue has gone away since doing this. However the problem still persists for OPM planets.

**Comment by Poodmund** [comment]
Open OPM/OPM_KopernicusSettings.cfg and change the entries to:
```
@Kopernicus:FOR[OPM]
{
	useOnDemand = False
	useManualMemoryManagement = false
}
```
... and see if that fixes the issue for you.

**Comment by davidson16807** [comment]
Hi, I just got my first opportunity in a while to try this. Looks like everything's working out okay. I'm guessing there's some sort of performance tradeoff that might prevent applying the fix to every install. I'll leave that issue up to you, but I think if this is properly documented somewhere then we can close out the issue.

**Comment by Poodmund** [comment]
Sorry, I didn't realise that you had responded to this issue. Unfortunately Module Manager cannot target Operating Systems and because of the user-base, target DirectX by default. I could include the above information in the 'Known Issues' section of the Readme for future releases? What do you think?

**Comment by davidson16807** [comment]
Hey, no problem. I only offer the idea as a suggestion. Yeah, README.md is a fine place and I think I would notice it there.

**Comment by Poodmund** [comment]
Closing as I don't think this is an issue anymore... haven't seen it reported in over a year.
