### ISSUE TITLE
Planets not showing

### ISSUE THREAD

**Issue by jkholzsager** [Galileo88/OPM_Galileo#21]
The outer planets aren't showing (native only) since the 1.5.1 update. Assume this is a conflict of some sort with Kopernicus, since it's not been updated yet, but just wanted to check if it should be working?

**Comment by Poodmund** [comment]
Kopernicus has not been updated to KSP 1.5.1 as of this time and will therefore not function on that version of KSP, as a result, OPM will also not function on that version. It says as much when you start up the game with Kopernicus installed for an incompatible version of KSP... you know, that popup that says so. 😛 

Please either downgrade your Kerbal install to a version that has a compatible version of Kopernicus available or be patient and wait for a new Kopernicus release.
