### ISSUE TITLE
OPM-Eeloo's normal map is still wrong.

### ISSUE THREAD

**Issue by WhirligigGirl** [Galileo88/OPM_Galileo#22]
![image](https://i.imgur.com/NWSzPhS.png)

For a couple versions of the original Outer Planets Mod, all of the normal maps were flipped due to a bug in KittopiaTech and/or dds conversion (I don't remember specifically, that was quite a while ago). While most of the planets were fixed, it seems that Eeloo's normal map is still flipped apparently North/South, with the light side of polar craters being on the wrong side.

**Comment by Poodmund** [comment]
Going forward from v2.2.3, Eeloo's normal map will **still** be correct.
