### ISSUE TITLE
OPM Custom Asteroids Config Issue

### ISSUE THREAD

**Issue by KSAMissionCtrl** [Galileo88/OPM_Galileo#23]
https://forum.kerbalspaceprogram.com/index.php?/topic/165854-ksp-15-outer-planets-mod221-25-april-2018/&do=findComment&comment=3519798

Was this looked at and is it a non-issue related to OPM? Still not getting any moonlets for anything but Dres in KSP v1.5.1 with the latest OPM (prior to the recent release which didn't mention this issue)

**Comment by Poodmund** [comment]
Fixed in this commit: https://github.com/Poodmund/Outer-Planets-Mod/commit/2c680bf9605d8027c3b3d2453f945a57dc9c25dc
