### ISSUE TITLE
The KSPedia entry doesn't work in KSP 1.8+

### ISSUE THREAD

**Issue by EngTurtle** [Galileo88/OPM_Galileo#26]
Seems they need to be rebundled with the new version of unity.
https://forum.kerbalspaceprogram.com/index.php?/topic/184789-131-18x-outer-planets-mod-v226-4th-feb-2020/&do=findComment&comment=3767078

This might help.
https://forum.kerbalspaceprogram.com/index.php?/topic/189355-kspedia-creation-impossible-with-180-parttools-solved/

**Comment by Poodmund** [comment]
This was on the radar but thank you for creating the issue so I do not forget. I have all the assets stored locally but I will need to set up a Unity build to recompile the assetbundle. I'll target this for next update.

**Comment by Poodmund** [comment]
I have the current KSPedia working in KSP 1.9.1. It contains all the graphics for the current body visuals... so if any are redone before next release I need to update the .assetbundle package.

**Comment by Poodmund** [comment]
This should be resolved in the latest 2.2.7 release. Please let me know otherwise.
