### ISSUE TITLE
Rings around Sarnus and Urlum are solid pink.

### ISSUE THREAD

**Issue by Esper89** [Galileo88/OPM_Galileo#46]
**Describe the bug**
The rings around Sarnus and Urlum are a solid striking pink color, reminding me of the typical stand-in for a missing texture.

**To Reproduce**
1. Install OPM on Linux via CKAN, including dependencies (Kopernicus, Module Manager, ModularFlightIntegrator).
2. Launch the game and visit the tracking station.
3. Enjoy the solid pink rings around Sarnus and Urlum.

**Expected behavior**
The rings around Sarnus and Urlum would look like typical rings around gas giants and ice giants respectively. They would be orange and grey respectively.

**Screenshots**
Sarnus:
![image](https://user-images.githubusercontent.com/69338029/96386040-de11a700-1165-11eb-80bf-4665c6ad67e5.png)
Urlum:
![image](https://user-images.githubusercontent.com/69338029/96386047-ea95ff80-1165-11eb-8b64-38a4b7bc248e.png)

**KSP Version & List of mods installed**
 - KSP v1.9.1 and KSP v1.10.1
 - Outer Planets Mod v2.2.8
 - Kopernicus v1.9.1-10 and Kopernicus UBE-42
 - Module Manager v4.1.4
 - ModularFlightIntegrator v1.2.7.0
 - Community Terrain Texture Pack v1.0.4
 - Custom Barn Kit v1.1.21.0

**Logs**
KSP v1.9.1: [1.9.1 Logs.zip](https://github.com/Poodmund/Outer-Planets-Mod/files/5398281/1.9.1.Logs.zip)
KSP v1.10.1: [1.10.1 Logs.zip](https://github.com/Poodmund/Outer-Planets-Mod/files/5398282/1.10.1.Logs.zip)

**Additional context**
 - I tried this using both the main Kopernicus branch and the "bleeding edge" one, on 1.9.1 and 1.10.1 respectively.
 - I tried both branches on two different computers each (both of them running Debian, both with newer Nvidia GPUs).
 - The files `Sarnus_ring.dds` and `Urlum_ring.dds` are both in `./GameData/OPM/OPM_Textures/PluginData/` where I've been told they should be, so it doesn't look like CKAN put them in the wrong directory.
 - The game is the native build for Linux, not the Windows build running in Wine.
 - ModularFlightIntegrator was only installed on the 1.9.1 version of the game (and therefore Kopernicus v1.9.1-10), as Kopernicus UBE-42 does not depend on it.

**Comment by Poodmund** [comment]
Hi, @Esper89, thanks for the report.

Try moving the two textures to the directory above i.e. OPM/OPM_Textures/Sarnus_ring.dds, and the same for Urlum, and then edit the two configs for Sarnus and Urlum on lines 120 and 99 respectively.

Try that and see if it resolves the issue for you.

**Comment by Esper89** [comment]
Unfortunately, this did not resolve the issue. I tested on both 1.9.1 and 1.10.1, on my previous testing savegames and on new savegames.

[1.9.1 Logs.zip](https://github.com/Poodmund/Outer-Planets-Mod/files/5433433/1.9.1.Logs.zip)
[1.10.1 Logs.zip](https://github.com/Poodmund/Outer-Planets-Mod/files/5433434/1.10.1.Logs.zip)

**Comment by lculibrk** [comment]
Chiming in to say I'm having the same issue. game ver. 1.9.1:

Modlist per CKAN
```
Astronomer's Visual Pack (AstronomersVisualPack 2:v4.05)
Astronomer's Visual Pack-2k Textures (AVP-2kTextures v1.11)
BetterBurnTime (BetterBurnTime 1.10)
BetterTimeWarpContinued (BetterTimeWarpCont 2.3.12.6)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.14)
CommNet Relays (ContractConfigurator-CommNetRelays v2.1.0)
Community Category Kit (CommunityCategoryKit 5.1.0.0)
Community Resource Pack (CommunityResourcePack 1.4.1.0)
Community Tech Tree (CommunityTechTree 1:3.4.2)
Contract Configurator (ContractConfigurator 1.28.0)
Contract Pack: Clever Sats (ContractConfigurator-CleverSats 1.4)
Contract Pack: Exploration Plus (ContractConfigurator-ExplorationPlus 2.0.1)
Contract Pack: Field Research (ContractConfigurator-FieldResearch 1.2.2)
Contract Pack: Tourism Plus (ContractConfigurator-Tourism 1.5.2)
Distant Object Enhancement Continued (DistantObject v2.0.1.1)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.1.1)
Environmental Visual Enhancements (EnvironmentalVisualEnhancements 3:1.10.1-3)
Filter Extensions - Plugin (FilterExtensions 3.2.6)
Flag Pack (FlagPack v1.1.1)
Interstellar Fuel Switch (InterstellarFuelSwitch 3.18)
Interstellar Fuel Switch Core (InterstellarFuelSwitch-Core 3.18)
Kerbal Attachment System (KAS 1.6)
Kerbal Inventory System (KIS 1.25)
KSC Switcher (KSCSwitcher v1.8.0.0)
KSP Interstellar Extended (KSPInterstellarExtended 1.25.31)
KSP Recall (KSP-Recall v0.0.4.4)
Module Manager (ModuleManager 4.1.4)
Photon Sailor (PhotonSailor 1.6.2.2)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
scatterer (Scatterer 3:v0.0632)
Scatterer Default Config (Scatterer-config 3:v0.0632)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0632)
TextureReplacer (TextureReplacer v4.2.3)
Toolbar Controller (ToolbarController 1:0.1.9.4)
TweakScale - Rescale Everything! (TweakScale v2.4.3.18)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)
```

additionally manually (not through CKAN) installed are Kopernicus and OPM.

**Comment by Poodmund** [comment]
This is reportedly a Kopernicus shader issue that is present for Linux/MacOS installs. Unfortunately this is outside of my remit to fix until the issue is resolved higher up the food chain. I'll leave this issue open but please ping me when this issue can be resolved in a future Kopernicus update.

**Comment by Poodmund** [comment]
@Esper89, the latest versions of Kopernicus (https://github.com/Kopernicus/Kopernicus/releases) have made changes to the ring shader on Mac/Linux. Would you be able to test these new builds to see whether it has resolved your issue?

**Comment by Poodmund** [comment]
& @lculibrk to that matter.

**Comment by Esper89** [comment]
Yes, this has resolved the issue, Sarnus looks amazing!
