### ISSUE TITLE
Neidon shows description of Nissee

### ISSUE THREAD

**Issue by terrabite3** [Galileo88/OPM_Galileo#5]
As the title says, Neidon shows the description of Nissee. Nissee also shows the same description. A brief perusal of the config files did not turn up any causes.

![image](https://user-images.githubusercontent.com/6559276/30044545-83ad688e-91b2-11e7-8894-aafcf5d2487e.png)

**Comment by Galileo88** [comment]
Ok i fixed this issue and merged your pull request for the smart quotes
