### ISSUE TITLE
Scatterer Configs

### ISSUE THREAD

**Issue by MeTeOrMaSh15** [Galileo88/OPM_Galileo#52]
I have OPM, Scatterer, EVE, Astronomer's visual pack
was trying to edit the atmosphere appearance configs in the Scatterer files (to make the atmospheres have less height to them) and I didn't see any configs for the OPM planets. Could you let me know where they are in the files and how to reach them, and/or make said configs editable please?

**Comment by MeTeOrMaSh15** [comment]
TL;DR how do i make the atmospheres for the planets/moons have less height
they go too high up
also Tekto has a weird black circle around it

**Comment by Poodmund** [comment]
Outer Planets Mod does not contain any configs for EVE or Scatterer. If you want visual configs for these mods, check out some of the visual mod packs like SVE or Spectra for 3rd party support.

**Comment by MeTeOrMaSh15** [comment]
@Poodmund hey so the config issue is fixed, the atmo configs are in the Astronomer's Visual Pack folder
but there's still the issue with Tekto
it has this weird black edge to it that doesn't quite reach through the atmosphere, but still noticable in the tracking station

**Comment by MeTeOrMaSh15** [comment]
![image](https://user-images.githubusercontent.com/43767152/182044084-3b5b6d00-0f02-4263-aa49-78f33b9c3ad8.png)

**Comment by Poodmund** [comment]
This is not an issue with this mod, please raise any issues that Astronomer's Visual Pack may have at its respective GitHub repository, forum thread or wherever issues for that mod are discussed.

**Comment by MeTeOrMaSh15** [comment]
ight thanks ill do that

**Comment by MeTeOrMaSh15** [comment]
@Poodmund ok so LGhassen was talking to me about the tekto outline issue and he has a question
is Outer Planets mod updated to be configurable with Scatterer 0.0800 and up? That might be the issue
