### ISSUE TITLE
OPM_RemoteTech patch needs NEEDS

### ISSUE THREAD

**Issue by Rodg88** [Galileo88/OPM_Galileo#7]
The RT compat patch doesn't have a "NEEDS[RemoteTech]", not sure if just having :AFTER[RemoteTech] is allowing other RT patches to trigger by initializing "RemoteTech" in MM, but probably best to add the NEEDS

**Comment by Sigma88** [comment]
``:AFTER[X]`` will not execute unless mod X is intalled, which means adding a ``:NEEDS[X]`` is redundant and not required
